In [ ]:
#"https://custom.resbank.co.za/SarbWebApi/mcm/Categories/"

In [10]:
import requests
import pandas as pd
import xml.etree.ElementTree as ET
import os
import datetime

In [11]:
setwd = os.chdir(r'C:\Users\Tlhogi\Documents\Grace\Investment Work\4. Sovereign Bonds\South Africa\Market_Rates')

In [12]:
api_url = "https://custom.resbank.co.za/SarbWebApi/MCM/Contributions/VALRATES"
response = requests.get(api_url)
if response.status_code == 200:
    data = response.json()
    print(data)
else:
    print(f"Failed to fetch data. Status code: {response.status_code}")

[{'Category': 'Valuation Rates', 'Description': 'Valuation Rates', 'Sequence': 1, 'Date': '2023-09-06T16:10:42.407', 'XMLData': '<MCMContribute type="VALRATES" date="2023-09-06 16:10:42"><Line><Column bdr="N" bold="Y"></Column><Column bdr="N" bold="Y"></Column></Line><Line><Column bdr="N" bold="Y">FOR ANY QUERIES CONTACT (012)313-4144</Column><Column bdr="N" bold="N"></Column></Line><Line><Column bdr="N" bold="N"></Column><Column bdr="N" bold="N"></Column></Line><Line><Column bdr="Y" bold="N">TIME</Column><Column bdr="Y" bold="N">2023-09-06</Column></Line><Line><Column bdr="Y" bold="N">I2031</Column><Column bdr="Y" bold="N">4.56</Column></Line><Line><Column bdr="Y" bold="N">R186</Column><Column bdr="Y" bold="N">9.08</Column></Line><Line><Column bdr="Y" bold="N">R197</Column><Column bdr="Y" bold="N">3.72</Column></Line><Line><Column bdr="Y" bold="N">R202</Column><Column bdr="Y" bold="N">4.80</Column></Line><Line><Column bdr="Y" bold="N">R2053</Column><Column bdr="Y" bold="N">12.51</Column></Line><Line><Column bdr="Y" bold="N">R204</Column><Column bdr="Y" bold="N">4.37</Column></Line><Line><Column bdr="Y" bold="N">R207</Column><Column bdr="Y" bold="N">9.95</Column></Line><Line><Column bdr="Y" bold="N">RN2027</Column><Column bdr="Y" bold="N">9.24</Column></Line><Line><Column bdr="Y" bold="N">R209</Column><Column bdr="Y" bold="N">12.05</Column></Line><Line><Column bdr="Y" bold="N">R210</Column><Column bdr="Y" bold="N">4.29</Column></Line><Line><Column bdr="Y" bold="N">R212</Column><Column bdr="Y" bold="N">1.69</Column></Line><Line><Column bdr="Y" bold="N">R213</Column><Column bdr="Y" bold="N">10.93</Column></Line><Line><Column bdr="Y" bold="N">R214</Column><Column bdr="Y" bold="N">12.46</Column></Line><Line><Column bdr="Y" bold="N">I2025</Column><Column bdr="Y" bold="N">4.27</Column></Line><Line><Column bdr="Y" bold="N">I2033</Column><Column bdr="Y" bold="N">4.79</Column></Line><Line><Column bdr="Y" bold="N">I2038</Column><Column bdr="Y" bold="N">5.04</Column></Line><Line><Column bdr="Y" bold="N">I2050</Column><Column bdr="Y" bold="N">5.06</Column></Line><Line><Column bdr="Y" bold="N">R2023</Column><Column bdr="Y" bold="N">7.44</Column></Line><Line><Column bdr="Y" bold="N">R2035</Column><Column bdr="Y" bold="N">11.97</Column></Line><Line><Column bdr="Y" bold="N">R2048</Column><Column bdr="Y" bold="N">12.59</Column></Line><Line><Column bdr="Y" bold="N">R2037</Column><Column bdr="Y" bold="N">12.32</Column></Line><Line><Column bdr="Y" bold="N">I2046</Column><Column bdr="Y" bold="N">5.04</Column></Line><Line><Column bdr="Y" bold="N">R2030</Column><Column bdr="Y" bold="N">10.40</Column></Line><Line><Column bdr="Y" bold="N">R2032</Column><Column bdr="Y" bold="N">11.25</Column></Line><Line><Column bdr="Y" bold="N">R2040</Column><Column bdr="Y" bold="N">12.59</Column></Line><Line><Column bdr="Y" bold="N">R2044</Column><Column bdr="Y" bold="N">12.68</Column></Line><Line><Column bdr="Y" bold="N">E170</Column><Column bdr="Y" bold="N">7.63</Column></Line><Line><Column bdr="Y" bold="N">R2044</Column><Column bdr="Y" bold="N">12.68</Column></Line><Line><Column bdr="Y" bold="N">E170</Column><Column bdr="Y" bold="N">7.63</Column></Line><Line><Column bdr="Y" bold="N">ES33</Column><Column bdr="Y" bold="N">12.67</Column></Line><Line><Column bdr="Y" bold="N">SZ25</Column><Column bdr="Y" bold="N">9.56</Column></Line><Line><Column bdr="Y" bold="N">WS04</Column><Column bdr="Y" bold="N">7.85</Column></Line><Line><Column bdr="Y" bold="N">TN27</Column><Column bdr="Y" bold="N">11.60</Column></Line><Line><Column bdr="Y" bold="N">I2029</Column><Column bdr="Y" bold="N">4.30</Column></Line><Line><Column bdr="Y" bold="N">RN2030</Column><Column bdr="Y" bold="N">9.50</Column></Line><Line><Column bdr="Y" bold="N">SARB DB 7 day</Column><Column bdr="Y" bold="N">0.00</Column></Line><Line><Column bdr="Y" bold="N">SARB DB 14 day</Column><Column bdr="Y" bold="N">0.00</Column></Line><Line><Column bdr="Y" bold="N">SARB DB 28 day</Column><Column bdr="Y" bold="N">0.00</Column></Line><Line><Column bdr="Y" bold="N">SARB DB 56 day</Column><Column bdr="Y" bold="N">0.00</Column></Line><Line><Column bdr="Y" bold="N">TB 0 - 91 DAYS</Column><Column bdr="Y" bold="N">8.34</Column></Line><Line><Column bdr="Y" bold="N">TB 92 - 182 DAYS</Column><Column bdr="Y" bold="N">8.47</Column></Line><Line><Column bdr="Y" bold="N">TB 183 - 273 DAYS</Column><Column bdr="Y" bold="N">8.46</Column></Line><Line><Column bdr="Y" bold="N">TB 364 DAYS</Column><Column bdr="Y" bold="N">8.24</Column></Line><Line><Column bdr="N" bold="Y">Overnight Fx Rates</Column><Column bdr="N" bold="N"></Column></Line><Line><Column bdr="Y" bold="N">%</Column><Column bdr="Y" bold="N">8.450</Column></Line><Line><Column bdr="Y" bold="N">R\'\'m</Column><Column bdr="Y" bold="N">7,360</Column></Line><Line><Column bdr="N" bold="Y">SABOR</Column><Column bdr="N" bold="N"></Column></Line><Line><Column bdr="Y" bold="N">%</Column><Column bdr="Y" bold="N">8.184</Column></Line><Line><Column bdr="Y" bold="N">R\'\'m</Column><Column bdr="Y" bold="N"> 42,755 </Column></Line></MCMContribute>'}]

In [13]:
df = pd.DataFrame(data)
df[:]

,Category,Description,Sequence,Date,XMLData
0,Valuation Rates,Valuation Rates,1,2023-09-06T16:10:42.407,"<MCMContribute type=""VALRATES"" date=""2023-09-0..."

In [14]:
xml_data = df["XMLData"].values[0]
print(xml_data)

<MCMContribute type="VALRATES" date="2023-09-06 16:10:42"><Line><Column bdr="N" bold="Y"></Column><Column bdr="N" bold="Y"></Column></Line><Line><Column bdr="N" bold="Y">FOR ANY QUERIES CONTACT (012)313-4144</Column><Column bdr="N" bold="N"></Column></Line><Line><Column bdr="N" bold="N"></Column><Column bdr="N" bold="N"></Column></Line><Line><Column bdr="Y" bold="N">TIME</Column><Column bdr="Y" bold="N">2023-09-06</Column></Line><Line><Column bdr="Y" bold="N">I2031</Column><Column bdr="Y" bold="N">4.56</Column></Line><Line><Column bdr="Y" bold="N">R186</Column><Column bdr="Y" bold="N">9.08</Column></Line><Line><Column bdr="Y" bold="N">R197</Column><Column bdr="Y" bold="N">3.72</Column></Line><Line><Column bdr="Y" bold="N">R202</Column><Column bdr="Y" bold="N">4.80</Column></Line><Line><Column bdr="Y" bold="N">R2053</Column><Column bdr="Y" bold="N">12.51</Column></Line><Line><Column bdr="Y" bold="N">R204</Column><Column bdr="Y" bold="N">4.37</Column></Line><Line><Column bdr="Y" bold="N">R207</Column><Column bdr="Y" bold="N">9.95</Column></Line><Line><Column bdr="Y" bold="N">RN2027</Column><Column bdr="Y" bold="N">9.24</Column></Line><Line><Column bdr="Y" bold="N">R209</Column><Column bdr="Y" bold="N">12.05</Column></Line><Line><Column bdr="Y" bold="N">R210</Column><Column bdr="Y" bold="N">4.29</Column></Line><Line><Column bdr="Y" bold="N">R212</Column><Column bdr="Y" bold="N">1.69</Column></Line><Line><Column bdr="Y" bold="N">R213</Column><Column bdr="Y" bold="N">10.93</Column></Line><Line><Column bdr="Y" bold="N">R214</Column><Column bdr="Y" bold="N">12.46</Column></Line><Line><Column bdr="Y" bold="N">I2025</Column><Column bdr="Y" bold="N">4.27</Column></Line><Line><Column bdr="Y" bold="N">I2033</Column><Column bdr="Y" bold="N">4.79</Column></Line><Line><Column bdr="Y" bold="N">I2038</Column><Column bdr="Y" bold="N">5.04</Column></Line><Line><Column bdr="Y" bold="N">I2050</Column><Column bdr="Y" bold="N">5.06</Column></Line><Line><Column bdr="Y" bold="N">R2023</Column><Column bdr="Y" bold="N">7.44</Column></Line><Line><Column bdr="Y" bold="N">R2035</Column><Column bdr="Y" bold="N">11.97</Column></Line><Line><Column bdr="Y" bold="N">R2048</Column><Column bdr="Y" bold="N">12.59</Column></Line><Line><Column bdr="Y" bold="N">R2037</Column><Column bdr="Y" bold="N">12.32</Column></Line><Line><Column bdr="Y" bold="N">I2046</Column><Column bdr="Y" bold="N">5.04</Column></Line><Line><Column bdr="Y" bold="N">R2030</Column><Column bdr="Y" bold="N">10.40</Column></Line><Line><Column bdr="Y" bold="N">R2032</Column><Column bdr="Y" bold="N">11.25</Column></Line><Line><Column bdr="Y" bold="N">R2040</Column><Column bdr="Y" bold="N">12.59</Column></Line><Line><Column bdr="Y" bold="N">R2044</Column><Column bdr="Y" bold="N">12.68</Column></Line><Line><Column bdr="Y" bold="N">E170</Column><Column bdr="Y" bold="N">7.63</Column></Line><Line><Column bdr="Y" bold="N">R2044</Column><Column bdr="Y" bold="N">12.68</Column></Line><Line><Column bdr="Y" bold="N">E170</Column><Column bdr="Y" bold="N">7.63</Column></Line><Line><Column bdr="Y" bold="N">ES33</Column><Column bdr="Y" bold="N">12.67</Column></Line><Line><Column bdr="Y" bold="N">SZ25</Column><Column bdr="Y" bold="N">9.56</Column></Line><Line><Column bdr="Y" bold="N">WS04</Column><Column bdr="Y" bold="N">7.85</Column></Line><Line><Column bdr="Y" bold="N">TN27</Column><Column bdr="Y" bold="N">11.60</Column></Line><Line><Column bdr="Y" bold="N">I2029</Column><Column bdr="Y" bold="N">4.30</Column></Line><Line><Column bdr="Y" bold="N">RN2030</Column><Column bdr="Y" bold="N">9.50</Column></Line><Line><Column bdr="Y" bold="N">SARB DB 7 day</Column><Column bdr="Y" bold="N">0.00</Column></Line><Line><Column bdr="Y" bold="N">SARB DB 14 day</Column><Column bdr="Y" bold="N">0.00</Column></Line><Line><Column bdr="Y" bold="N">SARB DB 28 day</Column><Column bdr="Y" bold="N">0.00</Column></Line><Line><Column bdr="Y" bold="N">SARB DB 56 day</Column><Column bdr="Y" bold="N">0.00</Column></Line><Line><Column bdr="Y" bold="N">TB 0 - 91 DAYS</Column><Column bdr="Y" bold="N">8.34</Column></Line><Line><Column bdr="Y" bold="N">TB 92 - 182 DAYS</Column><Column bdr="Y" bold="N">8.47</Column></Line><Line><Column bdr="Y" bold="N">TB 183 - 273 DAYS</Column><Column bdr="Y" bold="N">8.46</Column></Line><Line><Column bdr="Y" bold="N">TB 364 DAYS</Column><Column bdr="Y" bold="N">8.24</Column></Line><Line><Column bdr="N" bold="Y">Overnight Fx Rates</Column><Column bdr="N" bold="N"></Column></Line><Line><Column bdr="Y" bold="N">%</Column><Column bdr="Y" bold="N">8.450</Column></Line><Line><Column bdr="Y" bold="N">R''m</Column><Column bdr="Y" bold="N">7,360</Column></Line><Line><Column bdr="N" bold="Y">SABOR</Column><Column bdr="N" bold="N"></Column></Line><Line><Column bdr="Y" bold="N">%</Column><Column bdr="Y" bold="N">8.184</Column></Line><Line><Column bdr="Y" bold="N">R''m</Column><Column bdr="Y" bold="N"> 42,755 </Column></Line></MCMContribute>

In [15]:
print(type(xml_data))

<class 'str'>

In [16]:
root = ET.fromstring(xml_data)
print(root)

<Element 'MCMContribute' at 0x0000000011251680>

In [17]:
# Function to recursively print elements
def print_elements(element, indent=""):
    print(f"{indent}Tag: {element.tag}, Text: {element.text}")
    for child in element:
        print_elements(child, indent + "  ")

In [12]:
# Start the recursive printing from the root element
print_elements(root)

Tag: MCMContribute, Text: None
  Tag: Line, Text: None
    Tag: Column, Text: None
    Tag: Column, Text: None
  Tag: Line, Text: None
    Tag: Column, Text: FOR ANY QUERIES CONTACT (012)313-4144
    Tag: Column, Text: None
  Tag: Line, Text: None
    Tag: Column, Text: None
    Tag: Column, Text: None
  Tag: Line, Text: None
    Tag: Column, Text: TIME
    Tag: Column, Text: 2023-09-05
  Tag: Line, Text: None
    Tag: Column, Text: I2031
    Tag: Column, Text: 4.56
  Tag: Line, Text: None
    Tag: Column, Text: R186
    Tag: Column, Text: 9.05
  Tag: Line, Text: None
    Tag: Column, Text: R197
    Tag: Column, Text: 3.72
  Tag: Line, Text: None
    Tag: Column, Text: R202
    Tag: Column, Text: 4.77
  Tag: Line, Text: None
    Tag: Column, Text: R2053
    Tag: Column, Text: 12.49
  Tag: Line, Text: None
    Tag: Column, Text: R204
    Tag: Column, Text: 4.37
  Tag: Line, Text: None
    Tag: Column, Text: R207
    Tag: Column, Text: 9.95
  Tag: Line, Text: None
    Tag: Column, Text: RN2027
    Tag: Column, Text: 9.24
  Tag: Line, Text: None
    Tag: Column, Text: R209
    Tag: Column, Text: 11.99
  Tag: Line, Text: None
    Tag: Column, Text: R210
    Tag: Column, Text: 4.27
  Tag: Line, Text: None
    Tag: Column, Text: R212
    Tag: Column, Text: 1.69
  Tag: Line, Text: None
    Tag: Column, Text: R213
    Tag: Column, Text: 10.88
  Tag: Line, Text: None
    Tag: Column, Text: R214
    Tag: Column, Text: 12.43
  Tag: Line, Text: None
    Tag: Column, Text: I2025
    Tag: Column, Text: 4.26
  Tag: Line, Text: None
    Tag: Column, Text: I2033
    Tag: Column, Text: 4.78
  Tag: Line, Text: None
    Tag: Column, Text: I2038
    Tag: Column, Text: 5.02
  Tag: Line, Text: None
    Tag: Column, Text: I2050
    Tag: Column, Text: 5.01
  Tag: Line, Text: None
    Tag: Column, Text: R2023
    Tag: Column, Text: 7.44
  Tag: Line, Text: None
    Tag: Column, Text: R2035
    Tag: Column, Text: 11.90
  Tag: Line, Text: None
    Tag: Column, Text: R2048
    Tag: Column, Text: 12.58
  Tag: Line, Text: None
    Tag: Column, Text: R2037
    Tag: Column, Text: 12.26
  Tag: Line, Text: None
    Tag: Column, Text: I2046
    Tag: Column, Text: 5.01
  Tag: Line, Text: None
    Tag: Column, Text: R2030
    Tag: Column, Text: 10.39
  Tag: Line, Text: None
    Tag: Column, Text: R2032
    Tag: Column, Text: 11.20
  Tag: Line, Text: None
    Tag: Column, Text: R2040
    Tag: Column, Text: 12.57
  Tag: Line, Text: None
    Tag: Column, Text: R2044
    Tag: Column, Text: 12.66
  Tag: Line, Text: None
    Tag: Column, Text: E170
    Tag: Column, Text: 7.63
  Tag: Line, Text: None
    Tag: Column, Text: R2044
    Tag: Column, Text: 12.66
  Tag: Line, Text: None
    Tag: Column, Text: E170
    Tag: Column, Text: 7.63
  Tag: Line, Text: None
    Tag: Column, Text: ES33
    Tag: Column, Text: 12.61
  Tag: Line, Text: None
    Tag: Column, Text: SZ25
    Tag: Column, Text: 9.46
  Tag: Line, Text: None
    Tag: Column, Text: WS04
    Tag: Column, Text: 7.85
  Tag: Line, Text: None
    Tag: Column, Text: TN27
    Tag: Column, Text: 11.50
  Tag: Line, Text: None
    Tag: Column, Text: I2029
    Tag: Column, Text: 4.30
  Tag: Line, Text: None
    Tag: Column, Text: RN2030
    Tag: Column, Text: 9.50
  Tag: Line, Text: None
    Tag: Column, Text: SARB DB 7 day
    Tag: Column, Text: 0.00
  Tag: Line, Text: None
    Tag: Column, Text: SARB DB 14 day
    Tag: Column, Text: 0.00
  Tag: Line, Text: None
    Tag: Column, Text: SARB DB 28 day
    Tag: Column, Text: 0.00
  Tag: Line, Text: None
    Tag: Column, Text: SARB DB 56 day
    Tag: Column, Text: 0.00
  Tag: Line, Text: None
    Tag: Column, Text: TB 0 - 91 DAYS
    Tag: Column, Text: 8.34
  Tag: Line, Text: None
    Tag: Column, Text: TB 92 - 182 DAYS
    Tag: Column, Text: 8.47
  Tag: Line, Text: None
    Tag: Column, Text: TB 183 - 273 DAYS
    Tag: Column, Text: 8.46
  Tag: Line, Text: None
    Tag: Column, Text: TB 364 DAYS
    Tag: Column, Text: 8.24
  Tag: Line, Text: None
    Tag: Column, Text: Overnight Fx Rates
    Tag: Column, Text: None
  Tag: Line, Text: None
    Tag: Column, Text: %
    Tag: Column, Text: 8.400
  Tag: Line, Text: None
    Tag: Column, Text: R''m
    Tag: Column, Text: 927
  Tag: Line, Text: None
    Tag: Column, Text: SABOR
    Tag: Column, Text: None
  Tag: Line, Text: None
    Tag: Column, Text: %
    Tag: Column, Text: 8.182
  Tag: Line, Text: None
    Tag: Column, Text: R''m
    Tag: Column, Text:  43,379

In [19]:
# Iterate through the elements and extract Column and Text values
data = []

for line in root.findall(".//Line"):
    columns = line.findall("./Column")
    column_values = [col.text if col.text else "None" for col in columns]
    data.append(column_values)

print(data)

[['None', 'None'], ['FOR ANY QUERIES CONTACT (012)313-4144', 'None'], ['None', 'None'], ['TIME', '2023-09-06'], ['I2031', '4.56'], ['R186', '9.08'], ['R197', '3.72'], ['R202', '4.80'], ['R2053', '12.51'], ['R204', '4.37'], ['R207', '9.95'], ['RN2027', '9.24'], ['R209', '12.05'], ['R210', '4.29'], ['R212', '1.69'], ['R213', '10.93'], ['R214', '12.46'], ['I2025', '4.27'], ['I2033', '4.79'], ['I2038', '5.04'], ['I2050', '5.06'], ['R2023', '7.44'], ['R2035', '11.97'], ['R2048', '12.59'], ['R2037', '12.32'], ['I2046', '5.04'], ['R2030', '10.40'], ['R2032', '11.25'], ['R2040', '12.59'], ['R2044', '12.68'], ['E170', '7.63'], ['R2044', '12.68'], ['E170', '7.63'], ['ES33', '12.67'], ['SZ25', '9.56'], ['WS04', '7.85'], ['TN27', '11.60'], ['I2029', '4.30'], ['RN2030', '9.50'], ['SARB DB 7 day', '0.00'], ['SARB DB 14 day', '0.00'], ['SARB DB 28 day', '0.00'], ['SARB DB 56 day', '0.00'], ['TB 0 - 91 DAYS', '8.34'], ['TB 92 - 182 DAYS', '8.47'], ['TB 183 - 273 DAYS', '8.46'], ['TB 364 DAYS', '8.24'], ['Overnight Fx Rates', 'None'], ['%', '8.450'], ["R''m", '7,360'], ['SABOR', 'None'], ['%', '8.184'], ["R''m", ' 42,755 ']]

In [24]:
# Create a DataFrame from the extracted data
df = pd.DataFrame(data, columns=["Column", "Text"])

# Filter out rows where "None"
df = df[~df['Text'].isin(['None', '0.00'])]

# Reset the index
df.reset_index(drop=True, inplace=True)

# Print the DataFrame
print(df)

               Column        Text
0                TIME  2023-09-06
1               I2031        4.56
2                R186        9.08
3                R197        3.72
4                R202        4.80
5               R2053       12.51
6                R204        4.37
7                R207        9.95
8              RN2027        9.24
9                R209       12.05
10               R210        4.29
11               R212        1.69
12               R213       10.93
13               R214       12.46
14              I2025        4.27
15              I2033        4.79
16              I2038        5.04
17              I2050        5.06
18              R2023        7.44
19              R2035       11.97
20              R2048       12.59
21              R2037       12.32
22              I2046        5.04
23              R2030       10.40
24              R2032       11.25
25              R2040       12.59
26              R2044       12.68
27               E170        7.63
28              R2044       12.68
29               E170        7.63
30               ES33       12.67
31               SZ25        9.56
32               WS04        7.85
33               TN27       11.60
34              I2029        4.30
35             RN2030        9.50
36     TB 0 - 91 DAYS        8.34
37   TB 92 - 182 DAYS        8.47
38  TB 183 - 273 DAYS        8.46
39        TB 364 DAYS        8.24
40                  %       8.450
41               R''m       7,360
42                  %       8.184
43               R''m     42,755

In [27]:

# Add single quotation mark to 'Column' values that start with 'R'
#df['Column'] = df['Column'].apply(lambda x: "'" + x if x.startswith('R') else x)
df[:]

               Column        Text
0                TIME  2023-09-06
1               I2031        4.56
2                R186        9.08
3                R197        3.72
4                R202        4.80
5               R2053       12.51
6                R204        4.37
7                R207        9.95
8              RN2027        9.24
9                R209       12.05
10               R210        4.29
11               R212        1.69
12               R213       10.93
13               R214       12.46
14              I2025        4.27
15              I2033        4.79
16              I2038        5.04
17              I2050        5.06
18              R2023        7.44
19              R2035       11.97
20              R2048       12.59
21              R2037       12.32
22              I2046        5.04
23              R2030       10.40
24              R2032       11.25
25              R2040       12.59
26              R2044       12.68
27               E170        7.63
28              R2044       12.68
29               E170        7.63
30               ES33       12.67
31               SZ25        9.56
32               WS04        7.85
33               TN27       11.60
34              I2029        4.30
35             RN2030        9.50
36     TB 0 - 91 DAYS        8.34
37   TB 92 - 182 DAYS        8.47
38  TB 183 - 273 DAYS        8.46
39        TB 364 DAYS        8.24
40                  %       8.450
41               R''m       7,360
42                  %       8.184
43               R''m     42,755

In [28]:
# Get the current date
current_date = datetime.date.today()

# Calculate the date of the previous working day
if current_date.weekday() in {0, 5, 6}:  # Monday, Saturday, or Sunday
    previous_working_day = current_date - datetime.timedelta(days=3)
else:
    previous_working_day = current_date - datetime.timedelta(days=1)

# Format the date as YYYYMMDD
date_str = previous_working_day.strftime('%Y%m%d')

# Generate the CSV file name
csv_file_name = f'{date_str}_Rates.csv'

# Save the DataFrame to the CSV file
df.to_csv(csv_file_name)